name: Terraform test

inputs:
  version:
    description: 'install version of terraform'
    required: false
    default: latest
  api-token:
    description: 'Terraform Cloud API token'
    required: true
  directory:
    description: 'terraform directory'
    required: false
    default: terraform

runs:
  using: composite
  steps:
     - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ inputs.api-token }}
      - name: Terraform Init
        shell: bash
        run: terraform init

      - name: Check Format
        shell: bash
        run: terraform fmt --check
      - name: Terraform Validate
        shell: bash
        run: terraform validate --no-color
