name: Terraform test

inputs:
  directory:
    description: 'terraform directory'
    required: false
    default: terraform

runs:
  using: composite
  defaults:
    run:
      shell: bash
      working-directory: ${{ inputs.directory }}
  steps:
    - name: Terraform Init
      run: terraform init

    - name: Check Format
      run: terraform fmt --check
    - name: Terraform Validate
      run: terraform validate -no-color
