# Managed by terraform. https://github.com/hayas1/tfgh

changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - feature
    - title: '🔨 Breaking Changes'
      labels:
        - breaking
    - title: '🐛 Bug Fixes'
      labels:
        - bugfix
    - title: '🔧 Refactoring'
      labels:
        - refactor
    - title: '📖 Documentation'
      labels:
        - documentation
    - title: '👒 Dependency update'
      labels:
        - deps
    - title: '🧰 Maintenance'
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"

