name: Auto Pull Request

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: create-pull-request
        run: >
          gh pr create
          --title "into main from ${{ github.ref }}"
          --body 'Auto created pull request to `main`.'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pusher.name }}
        # continue-on-error: true
      # - run: echo "${{ steps.create-pull-request.outcome }} create new pull request"
  terraform:
    uses: hayas1/tfgh/.github/workflows/terraform.yml@modify/tfgh-terraform-workflow-script
    needs: create-pr
