name: Auto Pull Request

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-branch-ref: ${{ steps.pr-branch-ref.outputs.pr-ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        id: create-pull-request
        run: gh pr create -t "$TITLE" -b "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pusher.name }}
          TITLE: into main from ${{ github.ref }}
          BODY: Auto created pull request to `main`.
        continue-on-error: true
      - name: Get pull request branch ref
        id: pr-branch-ref
        run: echo "::set-output name=pr-ref::refs/pull/$(gh pr view --json number -q .number)/merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  terraform:
    uses: hayas1/tfgh/.github/workflows/terraform.yml@feat/tfgh-auto-pr
    needs: create-pr
    with:
      branch: ${{ needs.get-pr-branch.outputs.pr-branch-ref }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
