name: Terraform apply on push

on:
  push:
    branches: ["main"]

jobs:
  labels:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.labels-on-merge.outputs.labels }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/labels-on-merge
        id: labels-on-merge
        with:
          commit: ${{ github.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  apply:
    needs: labels
    if: contains(fromJson(needs.labels.outputs.label), 'manual') == false
    uses: ./.github/workflows/terraform.yml
    with:
      terraform: apply
    secrets: inherit
