name: Terraform apply on push

on:
  push:
    branches: ["main"]
  pull_request: # HACK
    branches: ["main"]

jobs:
  apply:
    uses: ./.github/workflows/terraform.yml
    with:
      terraform: apply
    secrets: inherit
