name: Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: plan
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          version: 1.9.8
          directory: terraform
          api-token: ${{ secrets.TF_API_TOKEN }}

      - uses: ./.github/actions/setup-tfcmt
        with:
          version: latest
      - name: Terraform Plan
        working-directory: terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tfcmt plan -patch -- terraform plan -no-color -input=false
